version: '3'
services:
    mongo:
        image: mongo
        ports:
            - "27018:27017"
    rabbitmq:
        image: rabbitmq
        ports: 
            - "5672:5672"
    producer:
        build: ./producer
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
    consumer:
        build: ./consumer
        depends_on:
            - rabbitmq
            - mongo
        links:
            - rabbitmq
            - mongo
